# Generated by Django 5.1 on 2024-08-14 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ["train"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["cargo", "seat"]},
        ),
        migrations.AddField(
            model_name="journey",
            name="crew",
            field=models.ManyToManyField(
                related_name="journey_trip", to="station.crew"
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journey_trip",
                to="station.route",
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journey_trip",
                to="station.train",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destinations",
                to="station.station",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="station.station",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="cargo",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="cargo_num",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="places_in_cargo",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="train_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trains",
                to="station.traintype",
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("source", "destination"), name="unique_train_route"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("journey", "cargo", "seat"), name="unique_journey_cargo_seat"
            ),
        ),
    ]
