# Generated by Django 5.1 on 2024-08-20 11:38

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_alter_journey_options_alter_ticket_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.train_image_file_path
            ),
        ),
    ]
